### ISSUE TITLE
nginx delegating serving assets to php

### ISSUE THREAD

**Issue by marcosh** [prooph/docker-files#1]
I tried to integrate [AssetManager](https://github.com/RWOverdijk/AssetManager) in a project I am working on and I discovered that it is not working because `nginx` handles directly static files and, if it doesn't find them, it returns a `404`, whitout asking anything to `php`.

This is caused by the [conf.d/location/expires.conf](https://github.com/prooph/docker-files/blob/master/nginx/www/config/conf.d/location/expires.conf) configuration file.

I am not at all an expert of `nginx` configuration, and I was wondering if it is possible to edit your provided configuration in such a way that, if a static file in not found, then the request is delegated to `php`.

**Comment by prolic** [comment]
in nginx you have `try_files`

see also: https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/

**Comment by marcosh** [comment]
thanks for the fast answer.

I know about `try_files` and that's what we are actually using.

The relevant part of our configuration is 

```
include conf.d/basic.conf;

location / {
    # Try to serve static file first, then redirect to index.
    try_files $uri $uri/ /index.php$is_args$args;
}

# Serve with PHP-FPM
location ~ \.php$ {
    ...
}
```

but, if I understand correctly how `nginx` works, the `try_files` in the `location /` is never reached when requesting a `.js` file because `nginx` uses the `location ~* \.(?:css|js)$` in your [conf.d/location/expires.conf](https://github.com/prooph/docker-files/blob/master/nginx/www/config/conf.d/location/expires.conf) configuration file.

At the moment my solution to the problem is avoid including your `expires.conf` file, but I was wondering if there was a better solution

**Comment by prolic** [comment]
problem comes from this

```
location ~ \.php$ {
```

it's .php file extension only

there is a massive amount of help for this topic on stackoverflow and the nginx manual.

**Comment by marcosh** [comment]
thanks a lot for the input!
sorry for bothering you, but, as I said, I'm not at all an `nginx` expert
