### ISSUE TITLE
php7.1-cli extends from xdebug

### ISSUE THREAD

**Issue by oqq** [prooph/docker-files#19]
This Dockerfile https://github.com/prooph/docker-files/blob/master/php/7.1-cli
extends from 7.1-cli-xdebug and
the Dockerfile https://github.com/prooph/docker-files/blob/master/php/7.1-cli-xdebug
extends from 7.1-cli

Not only this means we have an endless dependency loop here, but also all 7.1-cli images have xdebug activated by default.

**Comment by sandrokeil** [comment]
Good catch. :+1:  I guess we need a review process. Sorry for that.
