### ISSUE TITLE
add entrypoint and command to php cli

### ISSUE THREAD

**Issue by basz** [prooph/docker-files#20]
We should add this ending for each php-cli version. Like we do for composer https://github.com/prooph/docker-files/blob/master/composer/7.1-cli#L22-L24

```
# Set up the application directory
VOLUME ["/app"]
WORKDIR /app

# Set up the command arguments
CMD ["-"]
ENTRYPOINT ["php"]
```

will allow to do
`docker-compose -f docker-compose.yml run php bin/some-script.php`

instead of
`docker-compose -f docker-compose.yml run php php /app/bin/some-script.php`

**Comment by codeliner** [comment]
PR?

**Comment by sandrokeil** [comment]
The main reason for the current implementation is, that you can simply run other CLI commands too. If we change this, you have to override the entrypoint. Not sure if this is necessary for development here. Maybe we should instead add [an entrypoint definition](https://docs.docker.com/compose/compose-file/#entrypoint) to our Docker Compose file?

**Comment by basz** [comment]
I see. But do you do that? Run other commands then php with the php image?

Can always do -e “exec(‘ls’)” (sorry)

What your entry point definition does and how it can help I don’t know.

Edit: yes an entry point in the compose file would also achieve a similar behavior. You prefer that?

**Comment by sandrokeil** [comment]
> Edit: yes an entry point in the compose file would also achieve a similar behavior. You prefer that?

Yes, because it's not a "BC break".

**Comment by m9rco** [comment]
lz
