### ISSUE TITLE
latest composer version

### ISSUE THREAD

**Issue by nospor** [prooph/docker-files#22]
Hi,
Could you update your images in docker hub with the a little latest composer versions? It is quite important for symfony4 to have composer version which works proper with flex

**Comment by sandrokeil** [comment]
Sure. It's scheduled. Should be done within the next hours. See [build details](https://hub.docker.com/r/prooph/composer/builds/).

**Comment by nospor** [comment]
Cool, ta. When I did
docker pull prooph/composer:7.1
two days ago i got composer 1.5.5
I did it once more now and now is composer 1.6.3. thx :)
