### ISSUE TITLE
Q: soapy

### ISSUE THREAD

**Issue by basz** [prooph/docker-files#27]
ello, is there a reason prooph/docker-files enables the soap extension in all php images?

https://github.com/prooph/docker-files/commit/925253865307ebee284bda647005128e9f261466

https://github.com/search?l=&q=soap+user%3Aprooph&type=Commits

**Comment by prolic** [comment]
I guess because some want to use it? If you are not happy with the docker files, because you don't need all the extensions, just use it as blueprint.

**Comment by basz** [comment]
building my blue print indeed.  Just wondering if prooph software required it somehow but I don't believe so

**Comment by prolic** [comment]
No, just many extensions by default so it works most times out of the box

**Comment by sandrokeil** [comment]
It's only that some mostly used PHP extensions are available out of the box for the Docker images. Agree, no one uses SOAP here. :D
