### ISSUE TITLE
fix Alpine lib64 linking issue

### ISSUE THREAD

**Issue by sandrokeil** [prooph/docker-files#3]
Any idea why [this](https://github.com/prooph/docker-files/blob/master/php/7.0-cli#L65) is needed?

```
git clone --branch ${RABBITMQ_VERSION} https://github.com/alanxz/rabbitmq-c.git /tmp/rabbitmq \
        && cd /tmp/rabbitmq \
        && mkdir build && cd build \
        && cmake .. \
        && cmake --build . --target install \

        # workaround for linking issue
        && cp -r /usr/local/lib64/* /usr/lib/ \
```

**Comment by prolic** [comment]
Librabbitmq from this distro seems to be outdated.

Am 14.10.2016 04:54 schrieb "Sandro Keil" notifications@github.com:

**Comment by sandrokeil** [comment]
@prolic Have you any more details (which versions) or how to resolve this?

**Comment by prolic** [comment]
```
git clone git@github.com:alanxz/rabbitmq-c.git
cd rabbitmq-c
git checkout v0.7.1
autoreconf -i
./configure
make
make install
```

**Comment by sandrokeil** [comment]
I'm not sure what you mean, because I use the [latest v0.8.0 version](https://github.com/prooph/docker-files/blob/master/php/7.0-cli#L4).

**Comment by prolic** [comment]
Ok than I don't know what YOU mean. Is the question alpine Linux related?

Am 17.10.2016 04:20 schrieb "Sandro Keil" notifications@github.com:

**Comment by sandrokeil** [comment]
Yes it's Alpine Linux related. I have to copy the files from `/usr/local/lib64/*` to `/usr/lib/`, otherwise I can't build some PHP extenstions like _rabbitmq_. I'm note sure how I can change the build path for this or add this path to the known directories.

**Comment by prolic** [comment]
Make symlinks, not copies. Rest is okay like that.

Am 18.10.2016 03:43 schrieb "Sandro Keil" notifications@github.com:

**Comment by sandrokeil** [comment]
Solved with symlink
