### ISSUE TITLE
Support for php 7.4

### ISSUE THREAD

**Issue by MariusAmbr** [prooph/docker-files#44]
Do you have any plans to add support for php 7.4?

**Comment by sandrokeil** [comment]
Yes, we will add PHP 7.4. I‘m busy at the moment. Do you want to bring a PR? You can look at this [commit](https://github.com/prooph/docker-files/commit/70fc0244aa2549aa1b05948258fbcaeb708e8605). You can copy the PHP 7.3 files in the `m4` folder and modify it for PHP 7.4. Maybe only the `FROM` definition must be changed. Run `make` and you can compile the PHP 7.4 docker files.
