### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by dom235** [prooph/docker-files#48]
Hello and thank you for this awesome docker files. Are you planning to support PHP8 too?

Thanks in advance ❤️

**Comment by sandrokeil** [comment]
Yes, we will support PHP 8. The problem are the PHP extensions. Because we use many PHP extension and not all are ready for PHP 8 yet.

**Comment by dom235** [comment]
Oh yes indeed! It's too early to ask, you absolutely right.

Thanks for your reply. Stay healthy and keep up the good work!

**Comment by sandrokeil** [comment]
[PHP 8 Docker images](https://hub.docker.com/repository/docker/prooph/php/tags?page=1&ordering=last_updated) are on the way. Some extensions are disabled and will be enabled if they are ready.
