### ISSUE TITLE
composer 2.0

### ISSUE THREAD

**Issue by jay-knight** [prooph/docker-files#49]
Any plans to support composer 2.0? It might be nice to have images for 1.x and 2 so people can try out 2 but return to 1 if they need to. See https://blog.packagist.com/composer-2-0-is-now-available/

**Comment by sandrokeil** [comment]
Good idea, I will try to publish new Docker images this weekend.

**Comment by sandrokeil** [comment]
If you need Composer 1.x please use the tags with the suffix `-1x`
