### ISSUE TITLE
Blackfire probe not working with Alpine Linux

### ISSUE THREAD

**Issue by sandrokeil** [prooph/docker-files#5]
Seems Blackfire Probe (`blackfire.so`) is not supported for Alpine Linux or a library is missing:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/blackfire.so' - Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20151012/blackfire.so: backtrace_symbols: symbol not found in Unknown on line 0
PHP 7.0.11 (cli) (built: Sep 23 2016 17:39:54) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by oqq** [comment]
That is a documented behavior:
https://blackfire.io/docs/integrations/docker#enabling-the-php-probe

> Please note that the PHP Probe is not compatible with the alpine variants of PHP Docker images.

**Comment by sandrokeil** [comment]
Thanks for that hint. I didn't see it. Then we have to switch back to Ubuntu for these Docker images. 😞

**Comment by jpswade** [comment]
Do we know when Blackfire will be ready for Alpine?

**Comment by sandrokeil** [comment]
@jpswade Unfortunately not. You can ask the Blackfire support if there are any news about this.

**Comment by sandrokeil** [comment]
@jpswade Alpine Linux is [now supported](https://blog.blackfire.io/alpine-linux-support.html).

**Comment by jaymecd** [comment]
Any updates on integrating alpine probe?
If not, I could play and provide PR.

**Comment by sandrokeil** [comment]
@jaymecd Please do it. :+1:
