### ISSUE TITLE
new verison that support composer 2.0 has an issue when installing laravel

### ISSUE THREAD

**Issue by siverchen** [prooph/docker-files#51]
when I install laravel with new version of prooph/composer:7.3 that support composer 2.0, I had an error like below.

```
In PackageManifest.php line 122:
Undefined index: name
```

**Comment by sandrokeil** [comment]
I don‘t think it has something to do with the Docker image. You can use the Composer v1.x Docker image `prooph/composer:7.3-1x`. You can also create an issue in the Composer repository.
