### ISSUE TITLE
/app acts like a black hole

### ISSUE THREAD

**Issue by mlavrinenko** [prooph/docker-files#52]
I've faced a strange problem. Saving any data into /app produces nothing for image. Reproducing:

```bash
mkdir blackhole_app
cd blackhole_app
nano Dockerfile
```

```
FROM prooph/php:7.2-cli-xdebug

RUN echo "hello" > /app/hello.txt && ls -la /app # hello.txt exists
RUN ls -la /app # empty
```

```bash
docker build . --no-cache -t blackhole_app
docker run --rm blackhole_app ls -la /app # empty
```

ps. Using /var/www solves the problem, but why can't I use /app?
pps. There is no problem with `FROM composer:latest`

**Comment by sandrokeil** [comment]
You have to create your own [Dockerfile](https://docs.docker.com/engine/reference/builder/#volume) or you use another directory. Maybe you can set the `Volume` definition to empty before you copy your files.

> Changing the volume from within the Dockerfile: If any build steps change the data within the volume after it has been declared, those changes will be discarded.

**Comment by insideone** [comment]
@sandrokeil Thanks for clarifying!

**Comment by mlavrinenko** [comment]
@sandrokeil Thanks for clarifying!
