### ISSUE TITLE
Question about upgrading PHP releases

### ISSUE THREAD

**Issue by dom235** [prooph/docker-files#53]
Hello lovely prooph team!

Thank you again for this great toolbox. It's been a livesaver and works like a charm in production.

However, since we get new language features like ENUM in php 8.1, i would like to know if you are planning to keep the docker files for php8 updated and we get new docker releases?

Also i have seen, that the opcache extension has been removed caused by a bug introduced in php 8.0. See the following link: https://bugs.php.net/bug.php?id=80519

Last but not least i tweaked our docker build to support newer redis version like seen below:

FROM prooph/php:8.0-fpm
ENV PHP_REDIS_VERSION **5.3.2**

Using the newer redis version i was able to successfully build and run the container.

Many thanks for your feedback!

**Comment by sandrokeil** [comment]
I've updated the PHP Docker images to latest versions and added Redis + simdjson extension to PHP 8. At the moment there are no PHP 8.1 Docker images available but we will add them when they are available.

> Thank you again for this great toolbox. It's been a livesaver and works like a charm in production.

Great to hear that but keep in mind that these Docker images are for development. You can use them as a blueprint for your own Docker images but please don't rely on it for production.

**Comment by dom235** [comment]
Thank you Sir and no worries :) We read, understood and tweaked them to our needs. Running these for i think more than 6 months now in production without any issues.

Good work, keep it up!
