### ISSUE TITLE
Change Composer version on build time

### ISSUE THREAD

**Issue by ametad** [prooph/docker-files#57]
It would be great when the env `COMPOSER_VERSION` [here](https://github.com/prooph/docker-files/blob/838a85c6ee3361ec6e59ddc8917da18ac2663227/composer/inc/composer2.m4#L3), is changed to be an `ARG` so it can be changed in build time.

Would you be open for an pull request?

**Comment by ametad** [comment]
This way someone (I admit that would be me :wink:) could build a container locally, without the need to change the actual file. 

Like so:

```
$ docker build -t my-name/composer:7.4 -f 7.4-cli --build-arg COMPOSER_VERSION=2.2.7 https://github.com/prooph/docker-files.git#:composer
```

**Comment by codeliner** [comment]
Sounds good to me. What do you think @sandrokeil ?
