### ISSUE TITLE
./composer.json not found

### ISSUE THREAD

**Issue by ametad** [prooph/docker-files#62]
For years now I use the following snippet to run Composer on my Linux machine:

`$ docker run --rm -it --volume $(pwd):/app prooph/composer:7.4 [your composer command]`

Since today I got this error message:

> ./composer.json not found

Last week on Thursday I did not get the error.

I see there are some changes made in the past few days, is there something changed? For example is the `/app` path inside the container not the working dir anymore?

**Comment by ametad** [comment]
It will work when you explicitly set the working directory, e.g. with a docker run command:

`$ docker run --rm -it --volume $(pwd):/app --workdir /app prooph/composer:7.4 [your composer command]`

**Comment by sandrokeil** [comment]
It's a bug. It should have the default workdir set to `/app`. I will provide a fix.

**Comment by sandrokeil** [comment]
It's fixed, please pull the latest images.
