### ISSUE TITLE
Why is WORKDIR removed?

### ISSUE THREAD

**Issue by codeliner** [prooph/docker-files#7]
@sandrokeil I ran into trouble with the new docker images for php-7.x-alpine
I copy & pasted the prooph-do docker-compose to the new event-store-http-api project and wanted to use php-7.1-fpm-alpine using prooph/php:7.1-fpm

While trying to start the containers docker aborted with the message: `Container command 'php-fpm' not found or does not exist`

After some research I found the root of the problem:
I pointed the volume for the php container to `/var/www` like we do in prooph-do
but the official php container wants the workdir to point to `/var/www/html`
Before the switch to alpine we changed the workdir, see here: https://github.com/prooph/docker-files/commit/ad0b26fd08d1a0bcb870fc0db52e6c4a0aa4a72a#diff-4873419fc8793107febffc9a5ac7bb45L5

Why did you remove it? And why is prooph-do not updated? I guess every new user trying out prooph-do with docker will run into the same issue.

For now I solved the problem by pointing to `/var/www/html` but we should align either prooph-do or our docker files.

**Comment by sandrokeil** [comment]
That's a mistake. We should restore it for php-fpm. The [issue](https://github.com/prooph/proophessor-do/issues/85) for Docker update already exists.

**Comment by bweston92** [comment]
Can this be closed?

**Comment by sandrokeil** [comment]
Yes
