### ISSUE TITLE
Image for our CS fixer.

### ISSUE THREAD

**Issue by bweston92** [prooph/docker-files#8]

**Comment by sandrokeil** [comment]
@codeliner Can you create a new automated build on Docker hub with name `php-cs-test` please.

**Comment by codeliner** [comment]
@sandrokeil done, but build fails: https://hub.docker.com/r/prooph/php-cs-test/builds/bmcbmzwdzjkbtnx3doimqi6/

**Comment by sandrokeil** [comment]
@bweston92 Is the tag missing? Has this work for you?

**Comment by bweston92** [comment]
@sandrokeil should be working maybe it doesn't support named build steps.

**Comment by sandrokeil** [comment]
@bweston92 Looks like they have updated the Docker version. A [latest tag](https://hub.docker.com/r/prooph/php-cs-test/tags/) is now available.
